site_name: Flutter/Dart Standards
theme:
  name: material
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight

# Явно включаем все файлы
docs_dir: docs
extra:
  include_templates: true

nav:
  - Главная: index.md
  - Руководства:
    - Как писать правила: guides/writing-rules.md
    - Как контрибьютить: guides/contribution.md
    - Глоссарий: guides/glossary.md
  - Правила:
    - Dart:
      - Строгий конструктор: rules/dart/DART-DATA-REQ-CTOR.md
      - Factory при неполных данных: rules/dart/DART-DATA-FACTORY.md
      - Enum вместо чисел: rules/dart/DART-DATA-ENUM.md
      - Неизвестные значения enum: rules/dart/DART-DATA-ENUM-UNKNOWN.md
      - fromJson/toJson с enum.value: rules/dart/DART-DATA-JSON.md
      - Equatable для моделей: rules/dart/DART-DATA-EQUATABLE.md
      - Работа со списками: rules/dart/DART-LIST-SAFE-ACCESS.md
  - Соответствия:
    - Маппинг линтера: mappings/linter_rules.md
  - Шаблоны:
    - Обзор шаблонов: templates-docs/index.md
    - Руководство по шаблонам: templates-docs/templates-guide.md
    - Шаблон правила: templates-docs/rule-template.md
    - Шаблон PR: templates-docs/pr-template.md
    - Чек-лист PR: templates-docs/pr-checklist.md
    - GitHub Actions: templates-docs/pr-check.yml
