site_name: Flutter/Dart Standards
theme:
  name: material
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight
nav:
  - Главная: index.md
  - Руководства:
    - Как писать правила: guides/writing-rules.md
    - Как контрибьютить: guides/contribution.md
    - Глоссарий: guides/glossary.md
  - Правила:
    - Dart:
      - Строгий конструктор: rules/dart/DART-DATA-REQ-CTOR.md
      - Factory при неполных данных: rules/dart/DART-DATA-FACTORY.md
      - Enum вместо чисел: rules/dart/DART-DATA-ENUM.md
      - Неизвестные значения enum: rules/dart/DART-DATA-ENUM-UNKNOWN.md
      - fromJson/toJson с enum.value: rules/dart/DART-DATA-JSON.md
      - Equatable для моделей: rules/dart/DART-DATA-EQUATABLE.md
  - Соответствия:
    - Маппинг линтера: mappings/linter_rules.md
